services:
  web:
    container_name: azure-openai-express-demo
    image: node:14
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: node server.js